[package]
name = "solana-dex-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
teloxide = { version = "0.12.2", features = ["full"] }
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }
